### ISSUE TITLE
Cannot Import necessary libraries to access TangoData

### ISSUE THREAD

**Issue by ronz0215** [googlesamples/tango-examples-java#71]
In step 3 of the CameraPreview Tutorial Wiki the code shows loading libs which I do not see in the latest version of the SDK.  Have they been deprecated or is there another JAR/AAR file I need?  If they have been deprecated what it the last version that supported them?

import com.google.atap.tangoapi.VioStatus;
import com.google.atap.tangoclient.TangoCameraView;
import com.google.atap.tangoclient.TangoCameraView.OnStatusUpdateListener;
import com.google.atap.tangoclient.TangoClient;

**Comment by ronz0215** [comment]
@jguomoto @jfschmakeit   Could you take a look at this issue, not sure if it's related to issue #64 but it's another sample that doesn't compile "as is"

**Comment by jguomoto** [comment]
Hi @ronz0215, the tutorial is outdated on the wiki page, I've removed them. The code in should repo should be able to compile and run "out of the box".
