### ISSUE TITLE
Area description: relocalization status is set to true directly

### ISSUE THREAD

**Issue by jleuleu** [googlesamples/tango-examples-java#97]
When using the basic hello area description sample, the relocalization status is directly set to true at start. However, it should be set to true only when it is indeed relocalized with the ADF.
Apparently this happens since the Hopak release. Is this a regression problem of the Tango Core or is there a new way to detect the relocalization?

**Comment by realaboo** [comment]
+1  for the same issue.

**Comment by realaboo** [comment]
Updating Tango Core to the latest version resolves the problem.

**Comment by jleuleu** [comment]
Indeed, the latest Tango Core fixes the issue.
